"""Helpers for generating TrenchBroom maps from Python. Coordinates are world
metres: x along the level, y up, z sideways. TrenchBroom is Z-up in 32 units per
metre: TB (X, Y, Z) = (x, -z, y) * 32. Brushes use Quake winding, so they open
in TrenchBroom."""
import math

U = 32

def tb(x, y, z):
    return (x * U, -z * U, y * U)

def fmt(n):
    r = round(n, 3)
    return str(int(r)) if r == int(r) else f"{r}"

def cross(a, b):
    return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])

def norm(a):
    l = math.sqrt(sum(c*c for c in a)); return tuple(c/l for c in a)

def face(normal_tb, point_tb, tex):
    """A plane with outward normal: TB/Quake winding is normal = (p3-p1) x (p2-p1)."""
    n = norm(normal_tb)
    a = (0, 0, 1) if abs(n[2]) < 0.9 else (1, 0, 0)
    u = norm(cross(n, a))
    v = cross(n, u)  # u x v = n
    p1 = point_tb
    p2 = tuple(p1[i] + v[i]*64 for i in range(3))
    p3 = tuple(p1[i] + u[i]*64 for i in range(3))
    pts = " ".join("( " + " ".join(fmt(c) for c in p) + " )" for p in (p1, p2, p3))
    return f"{pts} {tex} 0 0 0 1 1"

def box(x0, x1, y0, y1, z0, z1, tex, top=None, bottom=None):
    """World-space axis-aligned box. `tex` for sides, `top`/`bottom` optional."""
    X0, X1 = x0*U, x1*U
    Y0, Y1 = -z1*U, -z0*U
    Z0, Z1 = y0*U, y1*U
    faces = [
        face((1, 0, 0), (X1, Y0, Z0), tex), face((-1, 0, 0), (X0, Y0, Z0), tex),
        face((0, 1, 0), (X0, Y1, Z0), tex), face((0, -1, 0), (X0, Y0, Z0), tex),
        face((0, 0, 1), (X0, Y0, Z1), top or tex), face((0, 0, -1), (X0, Y0, Z0), bottom or tex),
    ]
    return faces

def prism(cx, cz, r, y0, y1, sides, tex, top=None):
    """World-space vertical n-gon prism, vertices at radius r."""
    faces = []
    apothem = r * math.cos(math.pi / sides)
    for i in range(sides):
        ang = 2 * math.pi * (i + 0.5) / sides
        nx, nz = math.cos(ang), math.sin(ang)
        px, pz = cx + nx * apothem, cz + nz * apothem
        faces.append(face((nx, -nz, 0), tb(px, y0, pz), tex))
    faces.append(face((0, 0, 1), tb(cx, y1, cz), top or tex))
    faces.append(face((0, 0, -1), tb(cx, y0, cz), tex))
    return faces

def brush_text(faces):
    return "{\n" + "\n".join(faces) + "\n}"


class MapWriter:
    def __init__(self):
        self.entities = []

    def entity(self, props, brushes=()):
        self.entities.append((props, list(brushes)))

    def write(self, path):
        out = ["// Game: Generic", "// Format: Standard", "// Generated by a level script; safe to edit in TrenchBroom"]
        for i, (props, brushes) in enumerate(self.entities):
            out.append(f"// entity {i}")
            out.append("{")
            for k, v in props.items():
                out.append(f'"{k}" "{v}"')
            for j, b in enumerate(brushes):
                out.append(f"// brush {j}")
                out.append(brush_text(b))
            out.append("}")
        open(path, "w").write("\n".join(out) + "\n")
        print(f"{len(self.entities)} entities, {sum(len(b) for _, b in self.entities)} brushes")

def origin(x, y, z):
    """An entity origin property for a world-space point."""
    X, Y, Z = tb(x, y, z)
    return f"{fmt(X)} {fmt(Y)} {fmt(Z)}"
